apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lumen.fullname" . }}
  labels: {{- include "lumen.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.postgresdb.host) }}
  DB_HOST: "{{ .Values.postgresdb.host | b64enc }}"
  {{ else }}
  DB_HOST: {{ required "A DB Host is required!" .Values.postgresdb.host }}
  {{- end }}
  {{- if not (empty .Values.postgresdb.port) }}
  DB_PORT: "{{ .Values.postgresdb.port | b64enc }}"
  {{ else }}
  DB_PORT: "{{ "3306" | b64enc }}"
  {{- end }}
  {{- if not (empty .Values.postgresdb.user) }}
  DB_USERNAME: "{{ .Values.postgresdb.user | b64enc }}"
  {{ else }}
  DB_USERNAME: {{ required "A DB User is required!" .Values.postgresdb.user }}
  {{- end }}
  {{- if not (empty .Values.postgresdb.password) }}
  DB_PASSWORD: "{{ .Values.postgresdb.password | b64enc }}"
  {{ else }}
  DB_PASSWORD: {{ required "A DB Root Password is required!" .Values.postgresdb.password }}
  {{- end }}
  {{- if not (empty .Values.postgresdb.database) }}
  DB_DATABASE: "{{ .Values.postgresdb.database | b64enc }}"
  {{ else }}
  DB_DATABASE: {{ required "A DB Name is required!" .Values.postgresdb.database }}
  {{- end }}
  {{- if not (empty .Values.postgresdb.connection) }}
  DB_CONNECTION: "{{ .Values.postgresdb.connection | b64enc }}"
  {{ else }}
  DB_CONNECTION: {{ required "A DB Name is required!" .Values.postgresdb.connection }}
  {{- end }}
  APP_NAME: "{{ .Values.extraEnvs.appName | b64enc }}"
  APP_ENV: "{{ .Values.extraEnvs.appEnv | b64enc }}"
  APP_DEBUG: "{{ .Values.extraEnvs.appDebug | b64enc }}"
  APP_URL: "{{ .Values.extraEnvs.appUrl | b64enc }}"
  APP_TIMEZONE: "{{ .Values.extraEnvs.appTimezone | b64enc }}"
  LOG_CHANNEL: "{{ .Values.extraEnvs.logChannel | b64enc }}"
  CACHE_DRIVER: "{{ .Values.extraEnvs.cacheDriver | b64enc }}"
  QUEUE_CONNECTION: "{{ .Values.extraEnvs.queueConnection | b64enc }}"