apiVersion: v1
name: lumen-backend
version: 1.0.0
appVersion: 1.0.0
description: lumen helm chart
keywords:
  - lumen
  - php
home: https://drupal.org/
sources:
  - https://github.com/srijanone/
maintainers:
  - name: Srijan
    email: support@srijan.net
engine: gotpl
