on:
  push:
    branches:
      - master
      - stage
      - dev
name: CI
jobs:
  deploy:
    name: Docker Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
          image: rudranil29/drupal
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}